name: Run Python tests with Selenium and pytest on Ubuntu OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest selenium webdriver-manager allure-pytest pendulum 

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure

      - name: Run tests
        run: pytest
        continue-on-error: true

      - name: Generate Allure report
        run: allure generate ./allure-results

      - name: Upload Allure report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results
