name: Run Python tests with Selenium and pytest on Ubuntu OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest selenium webdriver-manager allure-pytest pytest-xdist pytest-rerunfailures pytz

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Allure CLI
        run: sudo apt-get install -y allure

      - name: Run tests
        run: pytest
        continue-on-error: true

      - name: Generate Allure report
        run: allure generate ./allure-results

      - name: Upload Allure report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: ./allure-results
